# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='latabbr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Abbreviation (Latin)'),
        ),
        migrations.AddField(
            model_name='book',
            name='latname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Latin)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='abbr',
            field=models.CharField(max_length=5, verbose_name='Abbreviation (English)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
    ]
