# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersearch',
            options={'verbose_name': 'User search', 'verbose_name_plural': 'User searches'},
        ),
    ]
