# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210510_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
    ]
