# Generated by Django 2.2 on 2023-01-26 10:02

from django.db import migrations, models
import passim.basic.models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_usersearch_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='IP address')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('created', models.DateTimeField(default=passim.basic.models.get_current_datetime)),
                ('path', models.TextField(blank=True, null=True, verbose_name='Path')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
            ],
        ),
    ]
