# Generated by Django 2.2 on 2021-08-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seeker', '0155_manuscript_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_researchsets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('setlisttype', models.CharField(choices=[('hist', 'Historical collection'), ('manu', 'Manuscript'), ('pers', 'Private dataset'), ('publ', 'Public dataset')], max_length=5, verbose_name='Setlist type')),
                ('contents', models.TextField(default='[]', verbose_name='Contents')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_setlists', to='seeker.Collection')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscript_setlists', to='seeker.Manuscript')),
                ('researchset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchset_setlists', to='dct.ResearchSet')),
            ],
        ),
    ]
