# Generated by Django 2.2 on 2021-08-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0155_manuscript_raw'),
        ('dct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchset',
            name='user',
        ),
        migrations.AddField(
            model_name='researchset',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_researchsets', to='seeker.Profile'),
            preserve_default=False,
        ),
    ]
