# Generated by Django 2.2 on 2021-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0002_auto_20210819_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='setlisttype',
            field=models.CharField(choices=[('hist', 'Historical collection'), ('manu', 'Manuscript'), ('ssgd', 'SSG dataset')], max_length=5, verbose_name='Setlist type'),
        ),
    ]
