# Generated by Django 2.2 on 2021-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0003_auto_20210823_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchset',
            name='contents',
            field=models.TextField(default='[]', verbose_name='Contents'),
        ),
    ]
