# Generated by Django 2.2 on 2021-08-23 13:58

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0004_researchset_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchset',
            name='contents',
        ),
        migrations.CreateModel(
            name='SetDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('contents', models.TextField(default='[]', verbose_name='Contents')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('researchset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchset_setdefs', to='dct.ResearchSet')),
            ],
        ),
    ]
