# Generated by Django 2.2 on 2021-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0005_auto_20210823_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdef',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
