# Generated by Django 2.2 on 2021-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0006_setdef_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchset',
            name='contents',
            field=models.TextField(default='[]', verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='setdef',
            name='contents',
            field=models.TextField(default='{}', verbose_name='Contents'),
        ),
    ]
