# Generated by Django 2.2 on 2021-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0007_auto_20210826_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='contents',
            field=models.TextField(default='{}', verbose_name='Contents'),
        ),
    ]
