# Generated by Django 2.2 on 2021-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0008_auto_20210826_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchset',
            name='scope',
            field=models.CharField(choices=[('priv', 'Private'), ('publ', 'Public'), ('team', 'Team')], default='priv', max_length=5, verbose_name='Scope'),
        ),
    ]
