# Generated by Django 2.2 on 2021-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0009_researchset_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setlist name'),
        ),
    ]
