# Generated by Django 2.2 on 2022-08-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0011_saveditem_savedsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveditem',
            old_name='setlisttype',
            new_name='sitemtype',
        ),
    ]
