# Generated by Django 2.2 on 2022-08-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0172_collection_comments'),
        ('dct', '0012_auto_20220815_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('selitemtype', models.CharField(choices=[('ssg', 'Authority File'), ('hist', 'Historical Collection'), ('manu', 'Manuscript'), ('pd', 'Personal Dataset'), ('serm', 'Sermon')], max_length=5, verbose_name='Select item type')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_selectitems', to='seeker.Collection')),
                ('equal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equal_selectitems', to='seeker.EqualGold')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscript_selectitems', to='seeker.Manuscript')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_selectitems', to='seeker.Profile')),
                ('sermon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermon_selectitems', to='seeker.SermonDescr')),
            ],
        ),
    ]
