# Generated by Django 2.2 on 2023-04-06 12:51

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0192_sermondescr_fullinfo'),
        ('dct', '0014_savedsearch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('visurl', models.CharField(max_length=255, verbose_name='Visualisation URL')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Parameters')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_savedvisualizations', to='seeker.Profile')),
            ],
        ),
    ]
