# Generated by Django 2.2 on 2023-05-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0015_savedvis'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectitem',
            name='saveditem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saveditem_selectitems', to='dct.SavedItem'),
        ),
        migrations.AlterField(
            model_name='selectitem',
            name='selitemtype',
            field=models.CharField(choices=[('ssg', 'Authority File'), ('hist', 'Historical Collection'), ('manu', 'Manuscript'), ('pd', 'Personal Dataset'), ('svdi', 'Saved Item'), ('serm', 'Sermon')], max_length=5, verbose_name='Select item type'),
        ),
    ]
