# Generated by Django 2.2 on 2023-06-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0196_auto_20230607_1012'),
        ('dct', '0016_auto_20230501_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_savegroups', to='seeker.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='saveditem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_saveditems', to='dct.SaveGroup'),
        ),
    ]
