# Generated by Django 2.2 on 2023-06-08 07:56

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0017_auto_20230607_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegroup',
            name='created',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
        migrations.AddField(
            model_name='savegroup',
            name='saved',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
    ]
