# Generated by Django 4.1 on 2024-05-29 12:27

from django.db import migrations, models
import django.db.models.deletion
import passim.dct.models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0216_equalgold_raw_alter_keyword_category'),
        ('dct', '0019_alter_researchset_id_alter_saveditem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('selitemtype', models.CharField(choices=[('ssg', 'Authority File'), ('hist', 'Historical Collection'), ('manu', 'Manuscript'), ('pd', 'Personal Dataset'), ('svdi', 'Saved Item'), ('serm', 'Sermon')], max_length=5, verbose_name='Select item type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Report')),
                ('excel', models.FileField(blank=True, null=True, upload_to=passim.dct.models.excel_import_path, verbose_name='Excel file')),
                ('status', models.CharField(choices=[('acc', 'Accepted'), ('chg', 'Changed'), ('cre', 'Created'), ('rej', 'Rejected'), ('sub', 'Submitted')], default='cre', max_length=5, verbose_name='Import status')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('equal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equal_importsetitems', to='seeker.equalgold')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscript_importsetitems', to='seeker.manuscript')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_importsetitems', to='seeker.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ImportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('acc', 'Accepted'), ('chg', 'Changed'), ('cre', 'Created'), ('rej', 'Rejected'), ('sub', 'Submitted')], default='cre', max_length=5, verbose_name='Review status')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('importset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importset_reviews', to='dct.importset')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_reviews', to='seeker.profile')),
            ],
        ),
    ]
