# Generated by Django 4.1 on 2024-05-30 06:44

from django.db import migrations, models
import passim.dct.models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0020_importset_importreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='importset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='importset',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to=passim.dct.models.import_path, verbose_name='Excel file'),
        ),
    ]
