# Generated by Django 4.1 on 2024-06-06 06:40

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0216_equalgold_raw_alter_keyword_category'),
        ('dct', '0024_alter_importreview_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('importset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importset_projects', to='dct.importset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importset_projects', to='seeker.project2')),
            ],
        ),
    ]
