# Generated by Django 4.1 on 2024-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0216_equalgold_raw_alter_keyword_category'),
        ('dct', '0025_importsetproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='importset',
            name='projects',
            field=models.ManyToManyField(related_name='projects_importset', through='dct.ImportSetProject', to='seeker.project2'),
        ),
    ]
