# Generated by Django 2.2 on 2023-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stemmaset',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Leitfehler data'),
        ),
        migrations.AddField(
            model_name='stemmaset',
            name='status',
            field=models.CharField(default='none', max_length=20, verbose_name='Status'),
        ),
    ]
