# Generated by Django 2.2 on 2023-06-30 04:49

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('stemma', '0002_auto_20230629_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmaset',
            name='data',
        ),
        migrations.RemoveField(
            model_name='stemmaset',
            name='status',
        ),
        migrations.CreateModel(
            name='StemmaCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Leitfehler data')),
                ('status', models.CharField(default='none', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('stemmaset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stemmaset_calcs', to='stemma.StemmaSet')),
            ],
        ),
    ]
