# Generated by Django 4.1 on 2024-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemma', '0006_alter_stemmacalc_id_alter_stemmaitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stemmaset',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
