# Generated by Django 2.2 on 2022-12-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField(verbose_name='Edition ID')),
                ('opera', models.IntegerField(verbose_name='Opera ID')),
                ('title', models.TextField(blank=True, default='', verbose_name='Title')),
                ('literaturtitel', models.TextField(blank=True, default='', verbose_name='Literature title')),
                ('pp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pages')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year')),
                ('band', models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume')),
                ('reihetitel', models.TextField(blank=True, default='', verbose_name='Series title')),
                ('reihekurz', models.TextField(blank=True, default='', verbose_name='Series short')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=255, verbose_name='Full name')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page')),
                ('line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line')),
                ('cap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cap')),
                ('explicit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Explicit')),
                ('incipit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Incipit')),
                ('huwaedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editionloci', to='reader.Edition')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='sauthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoreditions', to='reader.SimpleAuthor'),
        ),
        migrations.AddField(
            model_name='edition',
            name='slocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationeditions', to='reader.SimpleLocation'),
        ),
    ]
