# Generated by Django 2.2 on 2022-12-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='edition',
            new_name='editionid',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='band',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='literaturtitel',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='pp',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='reihekurz',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='reihetitel',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='sauthor',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='slocation',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='year',
        ),
        migrations.CreateModel(
            name='Literatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huwaid', models.IntegerField(verbose_name='Huwa ID')),
                ('huwatable', models.CharField(max_length=255, verbose_name='Huwa table name')),
                ('title', models.TextField(blank=True, default='', verbose_name='Title')),
                ('literaturtitel', models.TextField(blank=True, default='', verbose_name='Literature title')),
                ('pp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pages')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year')),
                ('band', models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume')),
                ('reihetitel', models.TextField(blank=True, default='', verbose_name='Series title')),
                ('reihekurz', models.TextField(blank=True, default='', verbose_name='Series short')),
                ('sauthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoreditions', to='reader.SimpleAuthor')),
                ('slocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationeditions', to='reader.SimpleLocation')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='literatur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='literatur_editions', to='reader.Literatur'),
            preserve_default=False,
        ),
    ]
