# Generated by Django 2.2 on 2023-01-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20221222_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='bis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seiten'),
        ),
        migrations.AddField(
            model_name='edition',
            name='bisattr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seiten'),
        ),
        migrations.AddField(
            model_name='edition',
            name='seiten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seiten'),
        ),
        migrations.AddField(
            model_name='edition',
            name='seitenattr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seiten'),
        ),
        migrations.AddField(
            model_name='edition',
            name='titel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seiten'),
        ),
    ]
