# Generated by Django 2.2 on 2023-01-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20230102_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiglenEdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigle')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('huwaedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editionsiglenedds', to='reader.Edition')),
                ('huwaliteratur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literatursiglenedds', to='reader.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Siglen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigle')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('huwaedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editionsiglens', to='reader.Edition')),
                ('huwahandschrift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handschriftsiglens', to='reader.Edition')),
            ],
        ),
    ]
