# Generated by Django 2.2 on 2023-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_siglen_siglenedd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siglen',
            name='huwahandschrift',
            field=models.IntegerField(verbose_name='HUWA Handschrift'),
        ),
        migrations.AlterField(
            model_name='siglenedd',
            name='huwaliteratur',
            field=models.IntegerField(verbose_name='HUWA Literatur'),
        ),
    ]
