# Generated by Django 2.2 on 2023-12-11 09:59

from django.db import migrations, models
import django.db.models.deletion
import passim.cms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('urlname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name in urls')),
                ('stype', models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status')),
                ('snote', models.TextField(default='[]', verbose_name='Status note(s)')),
                ('created', models.DateTimeField(default=passim.cms.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('htmlid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Htmlid')),
                ('stype', models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status')),
                ('snote', models.TextField(default='[]', verbose_name='Status note(s)')),
                ('created', models.DateTimeField(default=passim.cms.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_locations', to='cms.Cpage')),
            ],
        ),
        migrations.CreateModel(
            name='Citem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='Contents')),
                ('stype', models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status')),
                ('snote', models.TextField(default='[]', verbose_name='Status note(s)')),
                ('created', models.DateTimeField(default=passim.cms.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('clocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_items', to='cms.Clocation')),
            ],
        ),
    ]
