# Generated by Django 2.2 on 2023-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citem',
            name='original',
            field=models.TextField(blank=True, null=True, verbose_name='Original'),
        ),
    ]
