# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='testunit',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='testunit',
            name='participants',
            field=models.ManyToManyField(related_name='participant_testunits', to='enrich.Participant'),
        ),
    ]
