# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0002_auto_20200820_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(default='created', max_length=255, verbose_name='Status'),
        ),
    ]
