# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0003_participant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('round', models.IntegerField(default=0, verbose_name='Round')),
            ],
        ),
        migrations.RemoveField(
            model_name='testunit',
            name='participants',
        ),
        migrations.AddField(
            model_name='testunit',
            name='testsets',
            field=models.ManyToManyField(related_name='testset_testunits', to='enrich.Testset'),
        ),
    ]
