# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-24 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0004_auto_20200824_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='number',
        ),
    ]
