# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0005_remove_testset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
