# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-26 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0006_testset_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsetUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsetunits', to='enrich.Testset')),
            ],
        ),
        migrations.RemoveField(
            model_name='testunit',
            name='testsets',
        ),
        migrations.AddField(
            model_name='testsetunit',
            name='testunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsetunits', to='enrich.Testunit'),
        ),
    ]
