# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-27 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0008_testunit_testsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name or number code'),
        ),
    ]
