# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-07 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0010_auto_20200827_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=5, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testunit',
            name='ntype',
            field=models.CharField(choices=[('p', 'Natural'), ('n', 'Lombard noise')], max_length=5, verbose_name='Noise type'),
        ),
    ]
