# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrich', '0011_auto_20201007_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='testunit',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename'),
        ),
    ]
