# Generated by Django 4.1 on 2024-02-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddataset',
            name='status',
            field=models.CharField(choices=[], default='act', max_length=6, verbose_name='Board dataset status'),
            preserve_default=False,
        ),
    ]
