# Generated by Django 4.1 on 2024-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0002_boarddataset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddataset',
            name='status',
            field=models.CharField(choices=[('act', 'Active'), ('ina', 'Inactive')], default='act', max_length=6, verbose_name='Board dataset status'),
        ),
    ]
