# Generated by Django 4.1 on 2024-06-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0004_highlight_otype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('abbr', models.CharField(max_length=100, verbose_name='Name')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasetsermons', to='plugin.boarddataset')),
            ],
        ),
    ]
