# Generated by Django 4.1 on 2024-06-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0005_psermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psermon',
            name='abbr',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='Pmanuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('works', models.TextField(max_length=100, verbose_name='Works')),
                ('library', models.CharField(default='-', max_length=255, verbose_name='Library')),
                ('lcity', models.CharField(default='-', max_length=255, verbose_name='City')),
                ('idno', models.CharField(default='-', max_length=255, verbose_name='Idno')),
                ('lcountry', models.CharField(default='-', max_length=255, verbose_name='Country')),
                ('date', models.CharField(default='-', max_length=255, verbose_name='Date range')),
                ('total', models.IntegerField(default=0, verbose_name='Total number')),
                ('sermons', models.TextField(default='-', verbose_name='Sermons')),
                ('content', models.TextField(default='[]', verbose_name='Content')),
                ('ms_identifier', models.CharField(default='-', max_length=255, verbose_name='Shelfmark')),
                ('passim_ms_id', models.IntegerField(default=0, verbose_name='Century')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasetmanuscripts', to='plugin.boarddataset')),
            ],
        ),
    ]
