# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_edition_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='editype',
            field=models.CharField(choices=[('cl', 'Clavis'), ('gr', 'Gryson')], default='gr', max_length=5, verbose_name='Edition type'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='editype',
            field=models.CharField(choices=[('cl', 'Clavis'), ('gr', 'Gryson')], default='gr', max_length=5, verbose_name='Edition type'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edisignatures', to='seeker.Edition'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goldsignatures', to='seeker.SermonGold'),
        ),
    ]
