# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_auto_20190507_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='editype',
            field=models.CharField(choices=[('cl', 'Clavis'), ('gr', 'Gryson'), ('tst', 'Test')], default='gr', max_length=5, verbose_name='Edition type'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='editype',
            field=models.CharField(choices=[('cl', 'Clavis'), ('gr', 'Gryson'), ('tst', 'Test')], default='gr', max_length=5, verbose_name='Edition type'),
        ),
    ]
