# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-09 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_remove_sermongold_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='abbr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Abbreviation'),
        ),
    ]
