# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0006_author_abbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='editype',
        ),
        migrations.AddField(
            model_name='sermongold',
            name='bibliography',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliography'),
        ),
    ]
