# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0007_auto_20190513_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='edition',
        ),
    ]
