# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0009_edition_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftextlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Full text URL')),
            ],
        ),
        migrations.AddField(
            model_name='sermongold',
            name='critlinks',
            field=models.TextField(default='[]', verbose_name='Critical edition full text links'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='editype',
            field=models.CharField(choices=[('cl', 'Clavis'), ('gr', 'Gryson'), ('ot', 'Other')], default='gr', max_length=5, verbose_name='Edition type'),
        ),
        migrations.AddField(
            model_name='ftextlink',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goldftxtlinks', to='seeker.SermonGold'),
        ),
    ]
