# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 06:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seeker', '0010_auto_20190513_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('reptype', models.CharField(max_length=5, verbose_name='Report type')),
                ('contents', models.TextField(default='{}', verbose_name='Contents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='sermondescrgold',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('use', 'uses')], default='eq', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='sermongoldsame',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('use', 'uses')], default='eqs', max_length=5, verbose_name='Link type'),
        ),
    ]
