# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0014_profile_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='siglist',
            field=models.TextField(default='[]', verbose_name='List of signatures'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='srchexplicit',
            field=models.TextField(blank=True, null=True, verbose_name='Explicit (searchable)'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='srchincipit',
            field=models.TextField(blank=True, null=True, verbose_name='Incipit (searchable)'),
        ),
    ]
