# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0015_auto_20190527_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('editype', models.CharField(choices=[('cl', 'Clavis'), ('gr', 'Gryson'), ('ot', 'Other')], default='gr', max_length=5, verbose_name='Edition type')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermonsignatures', to='seeker.SermonDescr')),
            ],
        ),
    ]
