# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0016_sermonsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='manu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manusermons', to='seeker.Manuscript'),
        ),
    ]
