# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0017_sermondescr_manu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonman',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='sermonman',
            name='sermon',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='sermons',
        ),
        migrations.DeleteModel(
            name='SermonMan',
        ),
    ]
