# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0018_auto_20190527_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_manuscripts', to='seeker.Library'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_manuscripts', to='seeker.Origin'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeker.SourceInfo'),
        ),
        migrations.AlterField(
            model_name='nickname',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_nicknames', to='seeker.Author'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_sermons', to='seeker.Author'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='firstchild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermon_child', to='seeker.SermonDescr'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermon_next', to='seeker.SermonDescr'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='nickname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_sermons', to='seeker.Nickname'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermon_parent', to='seeker.SermonDescr'),
        ),
        migrations.AlterField(
            model_name='sermongold',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_goldensermons', to='seeker.Author'),
        ),
    ]
