# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0020_auto_20190606_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SermonGoldKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='sermongold',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_goldsermons', to='seeker.Author'),
        ),
        migrations.AddField(
            model_name='sermongoldkeyword',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermongold_kw', to='seeker.SermonGold'),
        ),
        migrations.AddField(
            model_name='sermongoldkeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermongold_kw', to='seeker.Keyword'),
        ),
        migrations.AddField(
            model_name='sermongold',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords_gold', through='seeker.SermonGoldKeyword', to='seeker.Keyword'),
        ),
    ]
