# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-13 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0022_manuscript_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='stype',
            field=models.CharField(default='-', max_length=5, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='stype',
            field=models.CharField(default='-', max_length=5, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='sermongold',
            name='stype',
            field=models.CharField(default='-', max_length=5, verbose_name='Status'),
        ),
    ]
