# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0023_auto_20190613_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EqualGoldLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linktype', models.CharField(choices=[('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('use', 'uses')], default='eqs', max_length=5, verbose_name='Link type')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalgold_dst', to='seeker.EqualGold')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalgold_src', to='seeker.EqualGold')),
            ],
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='stype',
            field=models.CharField(choices=[('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='stype',
            field=models.CharField(choices=[('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sermongold',
            name='stype',
            field=models.CharField(choices=[('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='relations',
            field=models.ManyToManyField(related_name='related_to', through='seeker.EqualGoldLink', to='seeker.EqualGold'),
        ),
        migrations.AddField(
            model_name='sermongold',
            name='equal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equal_goldsermons', to='seeker.EqualGold'),
        ),
    ]
