# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-20 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0024_auto_20190617_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Key name')),
                ('kvalue', models.TextField(blank=True, default='', null=True, verbose_name='Key value')),
            ],
        ),
    ]
