# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0026_auto_20190626_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_origins', to='seeker.City'),
        ),
        migrations.AddField(
            model_name='origin',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_origins', to='seeker.Country'),
        ),
        migrations.AddField(
            model_name='origin',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notes on this origin'),
        ),
        migrations.AddField(
            model_name='provenance',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_provenances', to='seeker.City'),
        ),
        migrations.AddField(
            model_name='provenance',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_provenances', to='seeker.Country'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reptype',
            field=models.CharField(choices=[('iecod', 'Import e-codices'), ('ig', 'Import gold sermon')], max_length=5, verbose_name='Report type'),
        ),
    ]
