# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0027_auto_20190626_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='extent',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Extent'),
        ),
    ]
