# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0028_auto_20190701_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (eng)')),
            ],
        ),
        migrations.CreateModel(
            name='LocationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('language', models.CharField(default='eng', max_length=100, verbose_name='Language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_names', to='seeker.Location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_locrelations', to='seeker.Location')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_locrelations', to='seeker.Location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('level', models.IntegerField(default=0, verbose_name='Hierarchy level')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='loctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.LocationType'),
        ),
        migrations.AddField(
            model_name='location',
            name='relations',
            field=models.ManyToManyField(related_name='relations_location', through='seeker.LocationRelation', to='seeker.Location'),
        ),
    ]
