# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0029_auto_20190701_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationname',
            name='idname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifier name'),
        ),
        migrations.AddField(
            model_name='locationname',
            name='idvalue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Identifier value'),
        ),
    ]
