# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0030_auto_20190704_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifier name')),
                ('idvalue', models.IntegerField(blank=True, null=True, verbose_name='Identifier value')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_identifiers', to='seeker.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='locationname',
            name='idname',
        ),
        migrations.RemoveField(
            model_name='locationname',
            name='idvalue',
        ),
    ]
