# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0031_auto_20190704_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_libraries', to='seeker.Location'),
        ),
    ]
