# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0032_library_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='lcity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcity_libraries', to='seeker.Location'),
        ),
        migrations.AddField(
            model_name='library',
            name='lcountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcountry_libraries', to='seeker.Location'),
        ),
    ]
