# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0033_auto_20190708_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_origins', to='seeker.Location'),
        ),
        migrations.AddField(
            model_name='provenance',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_provenances', to='seeker.Location'),
        ),
    ]
