# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0034_auto_20190708_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='city',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='country',
        ),
    ]
