# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0035_auto_20190708_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_libraries', to='seeker.City'),
        ),
    ]
