# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-21 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0036_auto_20190801_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='External URL')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptexternals', to='seeker.Manuscript')),
            ],
        ),
    ]
