# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0037_manuscriptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=255, verbose_name='Item ID')),
                ('abbr', models.CharField(blank=True, default='', max_length=100, verbose_name='Abbreviation')),
                ('full', models.TextField(blank=True, default='', verbose_name='Full reference')),
                ('short', models.TextField(blank=True, default='', verbose_name='Short reference')),
            ],
        ),
        migrations.CreateModel(
            name='LitrefMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_litrefs', to='seeker.Manuscript')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_litrefs', to='seeker.Litref')),
            ],
        ),
        migrations.AddField(
            model_name='manuscript',
            name='litrefs',
            field=models.ManyToManyField(through='seeker.LitrefMan', to='seeker.Litref'),
        ),
    ]
