# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-29 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0040_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='created',
            new_name='when',
        ),
    ]
