# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0041_auto_20190829_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='litrefman',
            name='pages',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pages'),
        ),
    ]
