# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-12 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0042_litrefman_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermondescr',
            old_name='edition',
            new_name='bibnotes',
        ),
    ]
