# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0043_auto_20190912_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub title'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='bibnotes',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliography notes'),
        ),
    ]
