# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0044_auto_20190912_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonDescrKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_kw', to='seeker.Keyword')),
            ],
        ),
        migrations.RemoveField(
            model_name='sermondescr',
            name='clavis',
        ),
        migrations.RemoveField(
            model_name='sermondescr',
            name='gryson',
        ),
        migrations.RemoveField(
            model_name='sermondescr',
            name='keyword',
        ),
        migrations.AddField(
            model_name='sermondescrkeyword',
            name='sermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_kw', to='seeker.SermonDescr'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords_sermon', through='seeker.SermonDescrKeyword', to='seeker.Keyword'),
        ),
    ]
