# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-30 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0045_auto_20190916_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='basketsize',
            field=models.IntegerField(default=0, verbose_name='Basket size'),
        ),
        migrations.AddField(
            model_name='basket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_contents', to='seeker.Profile'),
        ),
        migrations.AddField(
            model_name='basket',
            name='sermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_contents', to='seeker.SermonDescr'),
        ),
        migrations.AddField(
            model_name='profile',
            name='basketitems',
            field=models.ManyToManyField(related_name='basketitems_user', through='seeker.Basket', to='seeker.SermonDescr'),
        ),
    ]
