# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0046_auto_20190930_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitrefSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pages')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_litrefs_2', to='seeker.Litref')),
                ('sermon_gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_gold_litrefs', to='seeker.SermonGold')),
            ],
        ),
    ]
