# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0048_edirefsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='update',
            field=models.CharField(default='-', max_length=255, verbose_name='Update info'),
        ),
    ]
