# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-27 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0050_auto_20191127_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daterange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearstart', models.IntegerField(default=100, verbose_name='Year from')),
                ('yearfinish', models.IntegerField(default=100, verbose_name='Year until')),
                ('pages', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pages')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_dateranges', to='seeker.Manuscript')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_dateranges', to='seeker.Litref')),
            ],
        ),
    ]
