# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-23 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0055_auto_20191205_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionserm',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_col', to='seeker.Collection'),
        ),
        migrations.AddField(
            model_name='collectionserm',
            name='sermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_col', to='seeker.SermonDescr'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='collections',
            field=models.ManyToManyField(related_name='collections_sermon', through='seeker.CollectionSerm', to='seeker.Collection'),
        ),
    ]
