# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0057_auto_20200109_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='Editable'),
        ),
        migrations.AddField(
            model_name='author',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_equalgolds', to='seeker.Author'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='code',
            field=models.CharField(blank=True, default='DETERMINE', max_length=20, null=True, verbose_name='Passim code'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='moved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_ssg', to='seeker.EqualGold'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='sourceinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeker.Profile'),
        ),
    ]
