# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def copy_lib(apps, schema_editor):
    Manuscript = apps.get_model('seeker', 'Manuscript')
    for obj in Manuscript.objects.all():
        library = obj.library
        if library != None:
            obj.lcity = library.lcity
            obj.lcountry = library.lcountry
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0061_auto_20200423_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='lcity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcity_manuscripts', to='seeker.Location'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='lcountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcountry_manuscripts', to='seeker.Location'),
        ),
        migrations.RunPython(copy_lib)
    ]
