# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def copy_links(apps, schema_editor):
    SermonDescrGold = apps.get_model('seeker', 'SermonDescrGold')
    SermonDescrEqual = apps.get_model('seeker', 'SermonDescrEqual')
    for obj in SermonDescrGold.objects.all():
        sermon = obj.sermon
        linktype = obj.linktype
        super = obj.gold.equal
        eq = SermonDescrEqual.objects.filter(sermon=sermon, linktype=linktype, super=super).first()
        if eq == None:
            # Create it
            eq = SermonDescrEqual(sermon=sermon, linktype=linktype, super=super)
            eq.save()



class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0062_manu_lcity_lcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonDescrEqual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linktype', models.CharField(choices=[('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('use', 'uses')], default='eq', max_length=5, verbose_name='Link type')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_super', to='seeker.SermonDescr')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_super', to='seeker.EqualGold')),
            ],
        ),
        migrations.RunPython(copy_links)
    ]
