# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0063_sermondescrequal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualGoldKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('equal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_kw', to='seeker.EqualGold')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_kw', to='seeker.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='equalgold',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords_super', through='seeker.EqualGoldKeyword', to='seeker.Keyword'),
        ),
    ]
