# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0065_keyword_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='visibility',
            field=models.CharField(choices=[('all', 'All users'), ('edi', 'Editors only')], default='all', max_length=5, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='sermongoldkeyword',
            name='gold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_sermongold_kw', to='seeker.SermonGold'),
        ),
        migrations.AlterField(
            model_name='sermongoldkeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_sermongold_kw', to='seeker.Keyword'),
        ),
    ]
