# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0067_auto_20200513_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='-', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sermongold',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
    ]
