# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0068_auto_20200528_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
        migrations.AddField(
            model_name='sermongold',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
    ]
