# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-04 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0069_auto_20200529_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=50, verbose_name='Status abbreviation')),
                ('nameeng', models.CharField(max_length=50, verbose_name='Name (ENglish)')),
                ('namenld', models.CharField(max_length=50, verbose_name='Name (Dutch)')),
            ],
        ),
    ]
