# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models

def edit_size(apps, schema_editor):
    EqualGold = apps.get_model('seeker', 'EqualGold')
    for obj in EqualGold.objects.all():
        obj.sgcount = obj.equal_goldsermons.all().count()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0070_stype'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='sgcount',
            field=models.IntegerField(default=0, verbose_name='Equality set size'),
        ),
        migrations.RunPython(edit_size)
    ]
