# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models

def edit_signature(apps, schema_editor):
    EqualGold = apps.get_model('seeker', 'EqualGold')
    Signature = apps.get_model('seeker', 'Signature')
    for obj in EqualGold.objects.all():
        # Find out what the signatures are or what the first signature is
        first = Signature.objects.filter(gold__equal=obj).order_by('-editype', 'code').first()
        if first != None:
            obj.firstsig = first.code
            # Save changes
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0071_equalgold_sgcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='firstsig',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Code'),
        ),
        migrations.RunPython(edit_signature)
    ]
