# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models

def edit_signature(apps, schema_editor):
    EqualGold = apps.get_model('seeker', 'EqualGold')
    for obj in EqualGold.objects.all():
        # Check the firstsig field
        if obj.firstsig == "":
            obj.firstsig = None
            # Save changes
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0072_equalgold_firstsig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalgold',
            name='firstsig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.RunPython(edit_signature)
    ]
