# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import json

def edit_litref(apps, schema_editor):
    Litref = apps.get_model('seeker', 'Litref')
    for obj in Litref.objects.all():
        # Get the 'data' part
        data = obj.data
        if data != None and data != "":
            oData = json.loads(data)
            # Look for the 'date' field
            if 'date' in oData:
                str_year = oData['date'][-4:]
                try:
                    year = int(str_year)
                    obj.year = year
                    obj.save()
                except:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0073_auto_20200608_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='litref',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Publication year'),
        ),
        migrations.RunPython(edit_litref)
    ]
