# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0076_auto_20200622_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gold', 'gold'), ('manu', 'manuscript'), ('sermo', 'sermon'), ('super', 'super')], max_length=5, verbose_name='Type of user keyword')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_userkeywords', to='seeker.SermonGold')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kw_userkeywords', to='seeker.Keyword')),
                ('manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manu_userkeywords', to='seeker.Manuscript')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_userkeywords', to='seeker.Profile')),
                ('sermo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermo_userkeywords', to='seeker.SermonDescr')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_userkeywords', to='seeker.EqualGold')),
            ],
        ),
    ]
