# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-25 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0078_auto_20200625_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equalgoldkeyworduser',
            name='equal',
        ),
        migrations.RemoveField(
            model_name='equalgoldkeyworduser',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='equalgoldkeyworduser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='manuscriptkeyworduser',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='manuscriptkeyworduser',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptkeyworduser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sermondescrkeyworduser',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='sermondescrkeyworduser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sermondescrkeyworduser',
            name='sermon',
        ),
        migrations.RemoveField(
            model_name='sermongoldkeyworduser',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='sermongoldkeyworduser',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='sermongoldkeyworduser',
            name='profile',
        ),
        migrations.DeleteModel(
            name='EqualGoldKeywordUser',
        ),
        migrations.DeleteModel(
            name='ManuscriptKeywordUser',
        ),
        migrations.DeleteModel(
            name='SermonDescrKeywordUser',
        ),
        migrations.DeleteModel(
            name='SermonGoldKeywordUser',
        ),
    ]
