# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0079_auto_20200625_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='autype',
            field=models.CharField(default='ave', max_length=5, verbose_name='Author certainty'),
        ),
        migrations.AlterField(
            model_name='equalgoldlink',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('uns', 'unspecified'), ('use', 'uses')], default='eqs', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='sermondescrequal',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('uns', 'unspecified'), ('use', 'uses')], default='uns', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='sermondescrgold',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('uns', 'unspecified'), ('use', 'uses')], default='eq', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='sermongoldsame',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar_to'), ('uns', 'unspecified'), ('use', 'uses')], default='eqs', max_length=5, verbose_name='Link type'),
        ),
    ]
