# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0082_msitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermonhead',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
