# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0086_auto_20200723_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='settype',
            field=models.CharField(default='pd', max_length=5, verbose_name='Set type'),
        ),
    ]
