# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-03 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0087_collection_settype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='settype',
            field=models.CharField(choices=[('hc', 'Historical Collection'), ('pd', 'Personal Dataset')], default='pd', max_length=5, verbose_name='Set type'),
        ),
    ]
