# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0088_auto_20200803_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitrefCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pages')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_litrefcols', to='seeker.Collection')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_litrefcols', to='seeker.Litref')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='litrefs',
            field=models.ManyToManyField(related_name='litrefs_collection', through='seeker.LitrefCol', to='seeker.Litref'),
        ),
    ]
