# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0090_collection_snote'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
    ]
