# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0091_template_snote'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='created',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='created',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
    ]
