# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0094_collection_ssgauthornum'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='hccount',
            field=models.IntegerField(default=0, verbose_name='Historical Collection count'),
        ),
    ]
