# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0096_collection_overlap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollOverlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap', models.IntegerField(default=0, verbose_name='Overlap percentage')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='overlap',
        ),
        migrations.AddField(
            model_name='colloverlap',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_colloverlaps', to='seeker.Collection'),
        ),
        migrations.AddField(
            model_name='colloverlap',
            name='manuscript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manu_colloverlaps', to='seeker.Manuscript'),
        ),
        migrations.AddField(
            model_name='colloverlap',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_colloverlaps', to='seeker.Profile'),
        ),
    ]
