# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0097_auto_20200812_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colloverlap',
            name='created',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
        migrations.AddField(
            model_name='colloverlap',
            name='saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
