# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0099_auto_20200817_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
        migrations.AddField(
            model_name='location',
            name='snote',
            field=models.TextField(default='[]', verbose_name='Status note(s)'),
        ),
    ]
