# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0101_auto_20200827_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lcity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcity_locations', to='seeker.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='lcountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcountry_locations', to='seeker.Location'),
        ),
    ]
