# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0103_book_chapter_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='added',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Addition'),
        ),
        migrations.AddField(
            model_name='range',
            name='intro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Introducer'),
        ),
    ]
