# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-14 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0106_sermondescr_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
