# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-14 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20201001_1551'),
        ('seeker', '0107_manuscript_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chvslist', models.TextField(blank=True, null=True, verbose_name='Chapters and verses')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Introducer')),
                ('added', models.CharField(blank=True, max_length=255, null=True, verbose_name='Addition')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookbibranges', to='bible.Book')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermonbibranges', to='seeker.SermonDescr')),
            ],
        ),
    ]
