# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0108_bibrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkchvs', models.CharField(max_length=9, verbose_name='Bk/Ch/Vs')),
                ('bibrange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibrangeverses', to='seeker.BibRange')),
            ],
        ),
    ]
