# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-22 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0111_auto_20201022_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermondescr',
            name='feast',
        ),
    ]
