# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-22 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0112_remove_sermondescr_feast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermondescr',
            old_name='feastnew',
            new_name='feast',
        ),
    ]
