# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-28 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0114_auto_20201026_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='otype',
            field=models.CharField(default='-', max_length=100, verbose_name='Object type'),
        ),
    ]
