# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0115_comment_otype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonEqualDist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=100.0, verbose_name='Distance')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermonsuperdist', to='seeker.SermonDescr')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermonsuperdist', to='seeker.EqualGold')),
            ],
        ),
    ]
