# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0117_auto_20201105_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
