# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0118_keyword_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcemanuscripts', to='seeker.SourceInfo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reptype',
            field=models.CharField(choices=[('ixlsx', 'Import Excel'), ('iecod', 'Import e-codices'), ('ig', 'Import gold sermon')], max_length=5, verbose_name='Report type'),
        ),
    ]
