# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0119_auto_20210107_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpchoice',
            name='help_html',
            field=models.TextField(blank=True, null=True, verbose_name='One-line help'),
        ),
    ]
