# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0120_helpchoice_help_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpchoice',
            name='help_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link to more help'),
        ),
    ]
