# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0121_auto_20210113_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='provenance',
            name='manu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='manuprovenances', to='seeker.Manuscript'),
        ),
    ]
