# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-18 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0122_provenance_manu'),
    ]

    operations = [
        migrations.AddField(
            model_name='provenanceman',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Manuscript-specific provenance note'),
        ),
    ]
