# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-18 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0123_provenanceman_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provenance',
            name='manu',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='note',
        ),
    ]
