# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0125_equalgold_ssgcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_gold',
            field=models.TextField(default='[]', verbose_name='Search results Gold'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_manu',
            field=models.TextField(default='[]', verbose_name='Search results Manu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_sermo',
            field=models.TextField(default='[]', verbose_name='Search results Sermo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_super',
            field=models.TextField(default='[]', verbose_name='Search results Super'),
        ),
    ]
