# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0128_manuscriptcorpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptcorpus',
            name='super',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supercorpora', to='seeker.EqualGold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscriptcorpus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcecorpora', to='seeker.EqualGold'),
        ),
        migrations.AlterField(
            model_name='manuscriptcorpus',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetcorpora', to='seeker.EqualGold'),
        ),
    ]
