# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0130_manuscriptcorpus_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusManu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='manuscriptcorpus',
            name='manu',
        ),
        migrations.AddField(
            model_name='corpusmanu',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpuscorpus', to='seeker.ManuscriptCorpus'),
        ),
        migrations.AddField(
            model_name='corpusmanu',
            name='manu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manucorpus', to='seeker.Manuscript'),
        ),
    ]
