# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-10 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0134_equalgoldcorpus_equalgoldcorpusitem_manuscriptcorpuslock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equalgoldcorpus',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='equalgoldcorpus',
            name='ssg',
        ),
        migrations.RemoveField(
            model_name='equalgoldcorpusitem',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='equalgoldcorpusitem',
            name='equal',
        ),
        migrations.RemoveField(
            model_name='manuscriptcorpuslock',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='manuscriptcorpuslock',
            name='super',
        ),
        migrations.DeleteModel(
            name='EqualGoldCorpus',
        ),
        migrations.DeleteModel(
            name='EqualGoldCorpusItem',
        ),
        migrations.DeleteModel(
            name='ManuscriptCorpusLock',
        ),
    ]
