# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0135_auto_20210210_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualGoldCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfw', models.TextField(default='[]', verbose_name='Most frequent words')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('status', models.TextField(default='empty', verbose_name='Status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileequalcorpora', to='seeker.Profile')),
                ('ssg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssgequalcorpora', to='seeker.EqualGold')),
            ],
        ),
        migrations.CreateModel(
            name='EqualGoldCorpusItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(default='{}', verbose_name='Words')),
                ('authorname', models.TextField(default='empty', verbose_name="Author's name")),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpusitems', to='seeker.EqualGoldCorpus')),
                ('equal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssgcorpusequals', to='seeker.EqualGold')),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptCorpusLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('status', models.TextField(default='empty', verbose_name='Status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilecorpuslocks', to='seeker.Profile')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supercorpuslocks', to='seeker.EqualGold')),
            ],
        ),
    ]
