# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-11 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0136_equalgoldcorpus_equalgoldcorpusitem_manuscriptcorpuslock'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgoldcorpusitem',
            name='scount',
            field=models.IntegerField(default=0, verbose_name='Sermon count'),
        ),
    ]
