# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0137_equalgoldcorpusitem_scount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loctype',
            field=models.ForeignKey(default=passim.seeker.models.get_default_loctype, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='loctypelocations', to='seeker.LocationType'),
        ),
    ]
