# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0141_auto_20210318_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('field', models.CharField(max_length=255, verbose_name='Field')),
                ('main', models.CharField(max_length=255, verbose_name='Model')),
            ],
        ),
    ]
