# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0142_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.TextField(blank=True, null=True, verbose_name='Support')),
                ('extent', models.TextField(blank=True, max_length=255, null=True, verbose_name='Extent')),
                ('format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Format')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('pagefirst', models.IntegerField(default=0, verbose_name='First page')),
                ('pagelast', models.IntegerField(default=0, verbose_name='Last page')),
                ('stype', models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status')),
                ('snote', models.TextField(default='[]', verbose_name='Status note(s)')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptcodicounits', to='seeker.Manuscript')),
            ],
            options={
                'verbose_name_plural': 'Codicological units',
                'verbose_name': 'Codicological unit',
            },
        ),
    ]
