# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0143_codico'),
    ]

    operations = [
        migrations.AddField(
            model_name='codico',
            name='name',
            field=models.CharField(default='SUPPLY A NAME', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='codico',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
