# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0144_auto_20210510_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodicoKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceCod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Codico-specific provenance note')),
            ],
        ),
        migrations.AddField(
            model_name='codico',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_codicos', to='seeker.Origin'),
        ),
        migrations.AddField(
            model_name='daterange',
            name='codico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='codico_dateranges', to='seeker.Codico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provenancecod',
            name='codico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_provenances', to='seeker.Codico'),
        ),
        migrations.AddField(
            model_name='provenancecod',
            name='provenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_provenances', to='seeker.Provenance'),
        ),
        migrations.AddField(
            model_name='codicokeyword',
            name='codico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_kw', to='seeker.Codico'),
        ),
        migrations.AddField(
            model_name='codicokeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_kw', to='seeker.Keyword'),
        ),
    ]
