# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-12 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0146_auto_20210512_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='codico',
            name='yearfinish',
            field=models.IntegerField(default=100, verbose_name='Year until'),
        ),
        migrations.AddField(
            model_name='codico',
            name='yearstart',
            field=models.IntegerField(default=100, verbose_name='Year from'),
        ),
    ]
