# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-17 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0147_auto_20210512_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='msitem',
            name='codico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codicoitems', to='seeker.Codico'),
        ),
    ]
