# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0149_auto_20210519_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='codico',
            name='comments',
            field=models.ManyToManyField(related_name='comments_codi', to='seeker.Comment'),
        ),
    ]
