# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0150_codico_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('codico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codicoreconstructions', to='seeker.Codico')),
            ],
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='mtype',
            field=models.CharField(choices=[('man', 'Manifestation'), ('rec', 'Reconstruction'), ('tem', 'Template')], default='man', max_length=5, verbose_name='Manifestation type'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='mtype',
            field=models.CharField(choices=[('man', 'Manifestation'), ('rec', 'Reconstruction'), ('tem', 'Template')], default='man', max_length=5, verbose_name='Manifestation type'),
        ),
        migrations.AddField(
            model_name='reconstruction',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptreconstructions', to='seeker.Manuscript'),
        ),
    ]
