# Generated by Django 2.2 on 2021-08-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0154_auto_20210812_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw'),
        ),
    ]
