# Generated by Django 2.2 on 2021-11-29 17:42

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0155_manuscript_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SermonDescrProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_proj', to='seeker.Project2')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_proj', to='seeker.SermonDescr')),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_proj', to='seeker.Manuscript')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_proj', to='seeker.Project2')),
            ],
        ),
        migrations.CreateModel(
            name='EqualGoldProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('equal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_proj', to='seeker.EqualGold')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_proj', to='seeker.Project2')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_proj', to='seeker.Collection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_proj', to='seeker.Project2')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='projects',
            field=models.ManyToManyField(related_name='project2_collection', through='seeker.CollectionProject', to='seeker.Project2'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='projects',
            field=models.ManyToManyField(related_name='project2_equalgold', through='seeker.EqualGoldProject', to='seeker.Project2'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='projects',
            field=models.ManyToManyField(related_name='project2_manuscripts', through='seeker.ManuscriptProject', to='seeker.Project2'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='projects',
            field=models.ManyToManyField(related_name='project2_sermons', through='seeker.SermonDescrProject', to='seeker.Project2'),
        ),
    ]
