# Generated by Django 2.2 on 2021-12-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0156_auto_20211129_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginCod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Codico-specific origin note')),
                ('codico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_origins', to='seeker.Codico')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_origins', to='seeker.Origin')),
            ],
        ),
    ]
