# Generated by Django 2.2 on 2021-12-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0159_auto_20211213_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteditor',
            name='rights',
            field=models.CharField(choices=[('rdo', 'Read only'), ('edi', 'Reading and writing')], default='edi', max_length=5, verbose_name='Rights'),
        ),
    ]
