# Generated by Django 2.2 on 2021-12-15 13:46

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0160_auto_20211213_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='project2',
            name='created',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
        migrations.AddField(
            model_name='project2',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
