# Generated by Django 2.2 on 2022-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0165_auto_20220110_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='editornotes',
            field=models.TextField(blank=True, null=True, verbose_name='Editor notes (Dutch)'),
        ),
    ]
