# Generated by Django 2.2 on 2022-06-24 07:05

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0170_auto_20220411_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualGoldExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalid', models.IntegerField(default=0, verbose_name='External identifier')),
                ('externaltype', models.CharField(choices=[('huwop', 'HUWA Opera')], default='huwop', max_length=5, verbose_name='External type')),
                ('subset', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subset')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('equal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalexternals', to='seeker.EqualGold')),
            ],
        ),
    ]
