# Generated by Django 2.2 on 2022-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0172_collection_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ptype',
            field=models.CharField(choices=[('aed', 'Approved Editor'), ('akw', 'Approved keyword editor'), ('dev', 'Developer of this application'), ('usr', 'Simple user'), ('unk', 'Unknown')], default='unk', max_length=5, verbose_name='Profile status'),
        ),
    ]
