# Generated by Django 2.2 on 2022-10-19 08:16

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0173_auto_20221017_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CodicoScribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('codico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_scr', to='seeker.Codico')),
                ('scribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_scr', to='seeker.Scribe')),
            ],
        ),
        migrations.AddField(
            model_name='codico',
            name='scribes',
            field=models.ManyToManyField(related_name='scribes_codi', through='seeker.CodicoScribe', to='seeker.Scribe'),
        ),
    ]
