# Generated by Django 2.2 on 2022-10-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0174_auto_20221019_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='codicoscribe',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note on the scribe for this codico'),
        ),
        migrations.AddField(
            model_name='scribe',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note on the scribe for this codico'),
        ),
    ]
