# Generated by Django 2.2 on 2022-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0175_auto_20221019_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='external',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in external DB'),
        ),
    ]
