# Generated by Django 2.2 on 2022-10-19 09:37

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0176_scribe_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('external', models.IntegerField(blank=True, null=True, verbose_name='ID in external DB')),
            ],
        ),
        migrations.AlterField(
            model_name='scribe',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note on the scribe'),
        ),
        migrations.CreateModel(
            name='CodicoScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note on the script for this codico')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('codico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_sct', to='seeker.Codico')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codico_sct', to='seeker.Script')),
            ],
        ),
        migrations.AddField(
            model_name='codico',
            name='scripts',
            field=models.ManyToManyField(related_name='scripts_codi', through='seeker.CodicoScript', to='seeker.Script'),
        ),
    ]
