# Generated by Django 2.2 on 2022-10-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0177_auto_20221019_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='external',
            field=models.IntegerField(null=True, verbose_name='ID in external DB'),
        ),
    ]
