# Generated by Django 2.2 on 2022-10-20 08:42

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0179_auto_20221019_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonGoldExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalid', models.IntegerField(default=0, verbose_name='External identifier')),
                ('externaltype', models.CharField(choices=[('huwop', 'HUWA Opera')], default='huwop', max_length=5, verbose_name='External type')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goldexternals', to='seeker.SermonGold')),
            ],
        ),
    ]
