# Generated by Django 2.2 on 2022-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0181_sermongold_edinote'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='edinote',
            field=models.TextField(blank=True, null=True, verbose_name='Edition note'),
        ),
    ]
