# Generated by Django 2.2 on 2022-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0182_equalgold_edinote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermongold',
            name='retractationes',
            field=models.TextField(blank=True, null=True, verbose_name='Retractationes'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('super', 'authority file'), ('gold', 'gold'), ('manu', 'manuscript'), ('sermo', 'sermon')], max_length=5, verbose_name='Type of collection'),
        ),
        migrations.AlterField(
            model_name='userkeyword',
            name='type',
            field=models.CharField(choices=[('super', 'authority file'), ('gold', 'gold'), ('manu', 'manuscript'), ('sermo', 'sermon')], max_length=5, verbose_name='Type of user keyword'),
        ),
    ]
