# Generated by Django 2.2 on 2023-01-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0183_auto_20221110_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='fulltext',
            field=models.TextField(blank=True, null=True, verbose_name='Full text'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='srchfulltext',
            field=models.TextField(blank=True, null=True, verbose_name='Full text (searchable)'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='fulltext',
            field=models.TextField(blank=True, null=True, verbose_name='Full text'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='srchfulltext',
            field=models.TextField(blank=True, null=True, verbose_name='Full text (searchable)'),
        ),
    ]
