# Generated by Django 2.2 on 2023-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0184_auto_20230126_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reptype',
            field=models.CharField(choices=[('ixlsx', 'Import Excel'), ('ijson', 'Import JSON'), ('iecod', 'Import e-codices'), ('ig', 'Import gold sermon'), ('itreqg', 'Import transcription for a SSG')], max_length=5, verbose_name='Report type'),
        ),
    ]
