# Generated by Django 2.2 on 2023-03-02 07:38

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0185_auto_20230202_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(choices=[('edi', 'Project approval'), ('rdo', 'Read only')], default='edi', max_length=5, verbose_name='Rights')),
                ('status', models.CharField(choices=[('excl', 'Exclude'), ('incl', 'Include')], default='incl', max_length=5, verbose_name='Default assignment')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(related_name='projects_profile', through='seeker.ProjectApprover', to='seeker.Project2'),
        ),
        migrations.DeleteModel(
            name='ProjectEditor',
        ),
        migrations.AddField(
            model_name='projectapprover',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_editor', to='seeker.Profile'),
        ),
        migrations.AddField(
            model_name='projectapprover',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_editor', to='seeker.Project2'),
        ),
    ]
