# Generated by Django 2.2 on 2023-03-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0186_auto_20230302_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapprover',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approver', to='seeker.Profile'),
        ),
        migrations.AlterField(
            model_name='projectapprover',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approver', to='seeker.Project2'),
        ),
    ]
