# Generated by Django 2.2 on 2023-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0188_projecteditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.CharField(choices=[('con', 'Content'), ('ctx', 'Context'), ('man', 'Manuscript labelling'), ('met', 'Meta'), ('str', 'Structure')], default='con', max_length=5, verbose_name='Category'),
        ),
    ]
