# Generated by Django 2.2 on 2023-03-30 06:41

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0189_keyword_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='transcription',
            field=models.FileField(blank=True, null=True, upload_to=passim.seeker.models.transcription_path, verbose_name='TEI-P5 xml file'),
        ),
    ]
