# Generated by Django 2.2 on 2023-03-30 08:57

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0190_sermondescr_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='transcription',
            field=models.FileField(blank=True, null=True, upload_to=passim.seeker.models.transcription_eqgold_path, verbose_name='TEI-P5 xml file'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='transcription',
            field=models.FileField(blank=True, null=True, upload_to=passim.seeker.models.transcription_sermo_path, verbose_name='TEI-P5 xml file'),
        ),
    ]
