# Generated by Django 2.2 on 2023-04-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0191_auto_20230330_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='fullinfo',
            field=models.TextField(blank=True, null=True, verbose_name='Full text info'),
        ),
    ]
