# Generated by Django 2.2 on 2023-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0192_sermondescr_fullinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='srchsectiontitle',
            field=models.TextField(blank=True, null=True, verbose_name='Section title (searchable)'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='srchsubtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Sub title (searchable)'),
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='srchtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Title (searchable)'),
        ),
    ]
