# Generated by Django 2.2 on 2023-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0194_auto_20230517_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='fullinfo',
            field=models.TextField(blank=True, null=True, verbose_name='Full text info'),
        ),
    ]
