# Generated by Django 2.2 on 2023-06-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0195_equalgold_fullinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescr',
            name='sermocount',
            field=models.IntegerField(default=0, verbose_name='Number of related sermon manifestations'),
        ),
        migrations.CreateModel(
            name='SermonDescrLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linktype', models.CharField(choices=[('ech', 'echoes'), ('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('rel', 'related to'), ('sim', 'similar_to'), ('uns', 'unspecified'), ('use', 'uses')], default='rel', max_length=5, verbose_name='Link type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes on this link')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_dst', to='seeker.SermonDescr')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermondescr_src', to='seeker.SermonDescr')),
            ],
        ),
        migrations.AddField(
            model_name='sermondescr',
            name='relations',
            field=models.ManyToManyField(related_name='related_to', through='seeker.SermonDescrLink', to='seeker.SermonDescr'),
        ),
    ]
