# Generated by Django 2.2 on 2023-07-19 07:52

from django.db import migrations, models
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0198_commentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentresponse',
            name='saved',
            field=models.DateTimeField(default=passim.seeker.models.get_current_datetime),
        ),
    ]
