# Generated by Django 2.2 on 2023-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0199_commentresponse_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentresponse',
            name='status',
            field=models.TextField(default='empty', verbose_name='Status'),
        ),
    ]
