# Generated by Django 2.2 on 2023-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0200_commentresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentresponse',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible in overview'),
        ),
    ]
