# Generated by Django 2.2 on 2023-10-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0201_commentresponse_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaterangeHistColl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearstart', models.IntegerField(default=100, verbose_name='Year from')),
                ('yearfinish', models.IntegerField(default=100, verbose_name='Year until')),
                ('histcoll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histcoll_dateranges', to='seeker.Collection')),
            ],
        ),
    ]
