# Generated by Django 2.2 on 2023-10-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0202_daterangehistcoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibrange',
            name='equal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equalbibranges', to='seeker.EqualGold'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='bibleref',
            field=models.TextField(blank=True, null=True, verbose_name='Bible reference(s)'),
        ),
        migrations.AddField(
            model_name='equalgold',
            name='verses',
            field=models.TextField(blank=True, null=True, verbose_name='List of verses'),
        ),
        migrations.AlterField(
            model_name='bibrange',
            name='sermon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermonbibranges', to='seeker.SermonDescr'),
        ),
    ]
