# Generated by Django 2.2 on 2023-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0203_auto_20231004_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibrange',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
