# Generated by Django 4.1 on 2024-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0206_alter_action_id_alter_altpages_id_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editprojects',
            field=models.ManyToManyField(related_name='editprojects_profile', through='seeker.ProjectEditor', to='seeker.project2'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='mtype',
            field=models.CharField(choices=[('rec', 'Reconstruction'), ('man', 'Regular'), ('tem', 'Template')], default='man', max_length=5, verbose_name='Manifestation type'),
        ),
        migrations.AlterField(
            model_name='sermondescr',
            name='mtype',
            field=models.CharField(choices=[('rec', 'Reconstruction'), ('man', 'Regular'), ('tem', 'Template')], default='man', max_length=5, verbose_name='Manifestation type'),
        ),
    ]
