# Generated by Django 4.1 on 2024-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0207_profile_editprojects_alter_manuscript_mtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecteditor',
            name='status',
            field=models.CharField(choices=[('excl', 'Exclude'), ('incl', 'Include')], default='incl', max_length=5, verbose_name='Default assignment'),
        ),
    ]
