# Generated by Django 4.1 on 2024-04-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0209_equalgoldexternal_externaltextid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short name')),
                ('full', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
            ],
        ),
        migrations.AlterField(
            model_name='daterange',
            name='yearfinish',
            field=models.IntegerField(default=0, verbose_name='Year until'),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='yearstart',
            field=models.IntegerField(default=0, verbose_name='Year from'),
        ),
        migrations.AddField(
            model_name='collection',
            name='typename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typename_collections', to='seeker.collectiontype'),
        ),
    ]
