# Generated by Django 4.1 on 2024-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0210_collectiontype_alter_daterange_yearfinish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptexternal',
            name='externaltextid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External identifier (text)'),
        ),
    ]
