# Generated by Django 4.1 on 2024-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0212_alter_equalgoldlink_linktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermondescrequal',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('uns', 'unspecified')], default='uns', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='sermondescrgold',
            name='linktype',
            field=models.CharField(choices=[('eqs', 'equals'), ('neq', 'not equal'), ('prt', 'partially equals'), ('sim', 'similar'), ('use', 'uses')], default='eq', max_length=5, verbose_name='Link type'),
        ),
    ]
