# Generated by Django 4.1 on 2024-05-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0213_alter_sermondescrequal_linktype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simval', models.FloatField(default=1.0, verbose_name='Similarity value')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_manuscriptsimilars', to='seeker.manuscript')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_manuscriptsimilars', to='seeker.manuscript')),
            ],
        ),
    ]
