# Generated by Django 4.1 on 2024-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0214_manuscriptsimilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='similars',
            field=models.ManyToManyField(related_name='similar_to', through='seeker.ManuscriptSimilar', to='seeker.manuscript'),
        ),
    ]
