# Generated by Django 4.1 on 2024-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0215_manuscript_similars'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalgold',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='category',
            field=models.CharField(choices=[('con', 'Content'), ('ctx', 'Context'), ('man', 'Manuscript labelling'), ('met', 'Meta'), ('str', 'Structure'), ('top', 'Topic')], default='con', max_length=5, verbose_name='Category'),
        ),
    ]
