# Generated by Django 4.1 on 2024-06-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0217_sermonsignature_codesort_signature_codesort'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermondescrexternal',
            name='externaltextid',
            field=models.TextField(blank=True, null=True, verbose_name='External identifier (text)'),
        ),
    ]
