# Generated by Django 2.2 on 2021-12-20 10:31

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seeker', '0161_auto_20211215_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='Field name')),
                ('current', models.TextField(blank=True, null=True, verbose_name='Current value')),
                ('change', models.TextField(default='{}', verbose_name='Proposed value')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileproposals', to='seeker.Profile')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superproposals', to='seeker.EqualGold')),
            ],
        ),
    ]
