# Generated by Django 2.2 on 2022-01-03 14:11

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0164_equalgold_atype'),
        ('approve', '0002_equalchange_atype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('acc', 'Accepted'), ('def', 'Default'), ('mod', 'Modification needed'), ('rej', 'Rejected')], default='def', max_length=5, verbose_name='Approval')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeapprovals', to='approve.EqualChange')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileapprovals', to='seeker.Profile')),
            ],
        ),
    ]
