# Generated by Django 2.2 on 2022-01-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve', '0004_auto_20220110_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalchange',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
