# Generated by Django 2.2 on 2022-02-10 14:53

from django.db import migrations, models
import django.db.models.deletion
import passim.seeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0166_manuscript_editornotes'),
        ('approve', '0005_equalchange_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('acc', 'Accepted'), ('mod', 'Modification needed'), ('def', 'Pending'), ('rej', 'Rejected')], default='def', max_length=5, verbose_name='Approval')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileaddings', to='seeker.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectaddings', to='seeker.Project2')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equaladdings', to='seeker.EqualGold')),
            ],
        ),
        migrations.CreateModel(
            name='EqualAddApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('acc', 'Accepted'), ('mod', 'Modification needed'), ('def', 'Pending'), ('rej', 'Rejected')], default='def', max_length=5, verbose_name='Approval')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created', models.DateTimeField(default=passim.seeker.models.get_current_datetime)),
                ('saved', models.DateTimeField(blank=True, null=True)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addapprovals', to='approve.EqualAdd')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileaddapprovals', to='seeker.Profile')),
            ],
        ),
    ]
