# Generated by Django 2.2 on 2022-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve', '0006_equaladd_equaladdapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='equaladd',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('rem', 'Remove')], default='add', max_length=5, verbose_name='Action'),
        ),
    ]
