# Generated by Django 2.2 on 2022-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve', '0008_auto_20220228_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equaladd',
            name='action',
            field=models.CharField(choices=[('add', 'Add project'), ('del', 'Delete AF'), ('rem', 'Remove project')], default='add', max_length=5, verbose_name='Action'),
        ),
    ]
